comment:
  layout: "header, diff, changes, sunburst, suggestions, tree"
  require_changes: false
  require_head: false
  require_base: false
coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    patch: false
    project:
      default:
        threshold: 3%