version: "3.7"

services:
  postgres:
    image: postgres:13.6
    container_name: urlshrt_postgres
    restart: always
    environment:
      POSTGRES_USER: urlshrt
      POSTGRES_PASSWORD: urlshrt
      POSTGRES_DB: urlshrt
    volumes:
      - C:\postgresql\urlshrt:/var/lib/postgresql/data
    ports:
      - "3000:5432"
    command: [ "postgres", "-c", "log_statement=all" ]