// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: urlshrt.proto

package api

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{0}
}

type ReadOriginalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortened string `protobuf:"bytes,1,opt,name=shortened,proto3" json:"shortened,omitempty"`
}

func (x *ReadOriginalRequest) Reset() {
	*x = ReadOriginalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadOriginalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOriginalRequest) ProtoMessage() {}

func (x *ReadOriginalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOriginalRequest.ProtoReflect.Descriptor instead.
func (*ReadOriginalRequest) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{1}
}

func (x *ReadOriginalRequest) GetShortened() string {
	if x != nil {
		return x.Shortened
	}
	return ""
}

type ReadOriginalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original string `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
}

func (x *ReadOriginalReply) Reset() {
	*x = ReadOriginalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadOriginalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOriginalReply) ProtoMessage() {}

func (x *ReadOriginalReply) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOriginalReply.ProtoReflect.Descriptor instead.
func (*ReadOriginalReply) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{2}
}

func (x *ReadOriginalReply) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type CreateShortenedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original string `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
}

func (x *CreateShortenedRequest) Reset() {
	*x = CreateShortenedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortenedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenedRequest) ProtoMessage() {}

func (x *CreateShortenedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenedRequest.ProtoReflect.Descriptor instead.
func (*CreateShortenedRequest) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShortenedRequest) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type CreateShortenedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortened string `protobuf:"bytes,1,opt,name=shortened,proto3" json:"shortened,omitempty"`
}

func (x *CreateShortenedReply) Reset() {
	*x = CreateShortenedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortenedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenedReply) ProtoMessage() {}

func (x *CreateShortenedReply) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenedReply.ProtoReflect.Descriptor instead.
func (*CreateShortenedReply) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShortenedReply) GetShortened() string {
	if x != nil {
		return x.Shortened
	}
	return ""
}

type CreateShortenedFromBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original []*OriginalWithCorrelation `protobuf:"bytes,1,rep,name=original,proto3" json:"original,omitempty"`
}

func (x *CreateShortenedFromBatchRequest) Reset() {
	*x = CreateShortenedFromBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortenedFromBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenedFromBatchRequest) ProtoMessage() {}

func (x *CreateShortenedFromBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenedFromBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateShortenedFromBatchRequest) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShortenedFromBatchRequest) GetOriginal() []*OriginalWithCorrelation {
	if x != nil {
		return x.Original
	}
	return nil
}

type OriginalWithCorrelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original    string `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	Correlation string `protobuf:"bytes,2,opt,name=correlation,proto3" json:"correlation,omitempty"`
}

func (x *OriginalWithCorrelation) Reset() {
	*x = OriginalWithCorrelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OriginalWithCorrelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalWithCorrelation) ProtoMessage() {}

func (x *OriginalWithCorrelation) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalWithCorrelation.ProtoReflect.Descriptor instead.
func (*OriginalWithCorrelation) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{6}
}

func (x *OriginalWithCorrelation) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *OriginalWithCorrelation) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

type CreateShortenedFromBatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortened []*ShortenedWithCorrelation `protobuf:"bytes,1,rep,name=shortened,proto3" json:"shortened,omitempty"`
}

func (x *CreateShortenedFromBatchReply) Reset() {
	*x = CreateShortenedFromBatchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortenedFromBatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenedFromBatchReply) ProtoMessage() {}

func (x *CreateShortenedFromBatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenedFromBatchReply.ProtoReflect.Descriptor instead.
func (*CreateShortenedFromBatchReply) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{7}
}

func (x *CreateShortenedFromBatchReply) GetShortened() []*ShortenedWithCorrelation {
	if x != nil {
		return x.Shortened
	}
	return nil
}

type ShortenedWithCorrelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortened   string `protobuf:"bytes,1,opt,name=shortened,proto3" json:"shortened,omitempty"`
	Correlation string `protobuf:"bytes,2,opt,name=correlation,proto3" json:"correlation,omitempty"`
}

func (x *ShortenedWithCorrelation) Reset() {
	*x = ShortenedWithCorrelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenedWithCorrelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenedWithCorrelation) ProtoMessage() {}

func (x *ShortenedWithCorrelation) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenedWithCorrelation.ProtoReflect.Descriptor instead.
func (*ShortenedWithCorrelation) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{8}
}

func (x *ShortenedWithCorrelation) GetShortened() string {
	if x != nil {
		return x.Shortened
	}
	return ""
}

func (x *ShortenedWithCorrelation) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

type ReadUserURLsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalWithShortened []*OriginalWithShortened `protobuf:"bytes,1,rep,name=original_with_shortened,json=originalWithShortened,proto3" json:"original_with_shortened,omitempty"`
}

func (x *ReadUserURLsReply) Reset() {
	*x = ReadUserURLsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadUserURLsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUserURLsReply) ProtoMessage() {}

func (x *ReadUserURLsReply) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUserURLsReply.ProtoReflect.Descriptor instead.
func (*ReadUserURLsReply) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{9}
}

func (x *ReadUserURLsReply) GetOriginalWithShortened() []*OriginalWithShortened {
	if x != nil {
		return x.OriginalWithShortened
	}
	return nil
}

type OriginalWithShortened struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original  string `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	Shortened string `protobuf:"bytes,2,opt,name=shortened,proto3" json:"shortened,omitempty"`
}

func (x *OriginalWithShortened) Reset() {
	*x = OriginalWithShortened{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OriginalWithShortened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalWithShortened) ProtoMessage() {}

func (x *OriginalWithShortened) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalWithShortened.ProtoReflect.Descriptor instead.
func (*OriginalWithShortened) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{10}
}

func (x *OriginalWithShortened) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *OriginalWithShortened) GetShortened() string {
	if x != nil {
		return x.Shortened
	}
	return ""
}

type ReadAmountOfURLsAndUsersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlsAmount  int64 `protobuf:"varint,1,opt,name=urls_amount,json=urlsAmount,proto3" json:"urls_amount,omitempty"`
	UsersAmount int64 `protobuf:"varint,2,opt,name=users_amount,json=usersAmount,proto3" json:"users_amount,omitempty"`
}

func (x *ReadAmountOfURLsAndUsersReply) Reset() {
	*x = ReadAmountOfURLsAndUsersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAmountOfURLsAndUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAmountOfURLsAndUsersReply) ProtoMessage() {}

func (x *ReadAmountOfURLsAndUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAmountOfURLsAndUsersReply.ProtoReflect.Descriptor instead.
func (*ReadAmountOfURLsAndUsersReply) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{11}
}

func (x *ReadAmountOfURLsAndUsersReply) GetUrlsAmount() int64 {
	if x != nil {
		return x.UrlsAmount
	}
	return 0
}

func (x *ReadAmountOfURLsAndUsersReply) GetUsersAmount() int64 {
	if x != nil {
		return x.UsersAmount
	}
	return 0
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlsToDelete []string `protobuf:"bytes,1,rep,name=urls_to_delete,json=urlsToDelete,proto3" json:"urls_to_delete,omitempty"`
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshrt_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlshrt_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_urlshrt_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserURLsRequest) GetUrlsToDelete() []string {
	if x != nil {
		return x.UrlsToDelete
	}
	return nil
}

var File_urlshrt_proto protoreflect.FileDescriptor

var file_urlshrt_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x33, 0x0a,
	0x13, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x64, 0x22, 0x2f, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x22, 0x34, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x22, 0x34, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x22,
	0x5b, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x38, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x22, 0x57, 0x0a, 0x17,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x64, 0x22, 0x5a, 0x0a, 0x18, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64,
	0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x67, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x52, 0x0a, 0x17, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x64, 0x52, 0x15, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x22, 0x51, 0x0a, 0x15, 0x4f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x22, 0x63, 0x0a, 0x1d, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x52, 0x4c, 0x73, 0x41,
	0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b,
	0x75, 0x72, 0x6c, 0x73, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x75, 0x72, 0x6c, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x3d, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52,
	0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x75, 0x72, 0x6c,
	0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0c, 0x75, 0x72, 0x6c, 0x73, 0x54, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x32,
	0xc2, 0x03, 0x0a, 0x07, 0x55, 0x72, 0x6c, 0x73, 0x68, 0x72, 0x74, 0x12, 0x42, 0x0a, 0x0c, 0x52,
	0x65, 0x61, 0x64, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x4b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x64, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x18,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x46,
	0x72, 0x6f, 0x6d, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x46, 0x72,
	0x6f, 0x6d, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x52, 0x4c, 0x73, 0x12, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x55,
	0x52, 0x4c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x18, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x52, 0x4c, 0x73, 0x41, 0x6e,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x52, 0x4c, 0x73, 0x41, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_urlshrt_proto_rawDescOnce sync.Once
	file_urlshrt_proto_rawDescData = file_urlshrt_proto_rawDesc
)

func file_urlshrt_proto_rawDescGZIP() []byte {
	file_urlshrt_proto_rawDescOnce.Do(func() {
		file_urlshrt_proto_rawDescData = protoimpl.X.CompressGZIP(file_urlshrt_proto_rawDescData)
	})
	return file_urlshrt_proto_rawDescData
}

var file_urlshrt_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_urlshrt_proto_goTypes = []interface{}{
	(*Empty)(nil),                           // 0: api.Empty
	(*ReadOriginalRequest)(nil),             // 1: api.ReadOriginalRequest
	(*ReadOriginalReply)(nil),               // 2: api.ReadOriginalReply
	(*CreateShortenedRequest)(nil),          // 3: api.CreateShortenedRequest
	(*CreateShortenedReply)(nil),            // 4: api.CreateShortenedReply
	(*CreateShortenedFromBatchRequest)(nil), // 5: api.CreateShortenedFromBatchRequest
	(*OriginalWithCorrelation)(nil),         // 6: api.OriginalWithCorrelation
	(*CreateShortenedFromBatchReply)(nil),   // 7: api.CreateShortenedFromBatchReply
	(*ShortenedWithCorrelation)(nil),        // 8: api.ShortenedWithCorrelation
	(*ReadUserURLsReply)(nil),               // 9: api.ReadUserURLsReply
	(*OriginalWithShortened)(nil),           // 10: api.OriginalWithShortened
	(*ReadAmountOfURLsAndUsersReply)(nil),   // 11: api.ReadAmountOfURLsAndUsersReply
	(*DeleteUserURLsRequest)(nil),           // 12: api.DeleteUserURLsRequest
}
var file_urlshrt_proto_depIdxs = []int32{
	6,  // 0: api.CreateShortenedFromBatchRequest.original:type_name -> api.OriginalWithCorrelation
	8,  // 1: api.CreateShortenedFromBatchReply.shortened:type_name -> api.ShortenedWithCorrelation
	10, // 2: api.ReadUserURLsReply.original_with_shortened:type_name -> api.OriginalWithShortened
	1,  // 3: api.Urlshrt.ReadOriginal:input_type -> api.ReadOriginalRequest
	3,  // 4: api.Urlshrt.CreateShortened:input_type -> api.CreateShortenedRequest
	5,  // 5: api.Urlshrt.CreateShortenedFromBatch:input_type -> api.CreateShortenedFromBatchRequest
	0,  // 6: api.Urlshrt.ReadUserURLs:input_type -> api.Empty
	0,  // 7: api.Urlshrt.ReadAmountOfURLsAndUsers:input_type -> api.Empty
	12, // 8: api.Urlshrt.DeleteUserURLs:input_type -> api.DeleteUserURLsRequest
	2,  // 9: api.Urlshrt.ReadOriginal:output_type -> api.ReadOriginalReply
	4,  // 10: api.Urlshrt.CreateShortened:output_type -> api.CreateShortenedReply
	7,  // 11: api.Urlshrt.CreateShortenedFromBatch:output_type -> api.CreateShortenedFromBatchReply
	9,  // 12: api.Urlshrt.ReadUserURLs:output_type -> api.ReadUserURLsReply
	11, // 13: api.Urlshrt.ReadAmountOfURLsAndUsers:output_type -> api.ReadAmountOfURLsAndUsersReply
	0,  // 14: api.Urlshrt.DeleteUserURLs:output_type -> api.Empty
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_urlshrt_proto_init() }
func file_urlshrt_proto_init() {
	if File_urlshrt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_urlshrt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadOriginalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadOriginalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortenedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortenedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortenedFromBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OriginalWithCorrelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortenedFromBatchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenedWithCorrelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadUserURLsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OriginalWithShortened); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAmountOfURLsAndUsersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshrt_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_urlshrt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urlshrt_proto_goTypes,
		DependencyIndexes: file_urlshrt_proto_depIdxs,
		MessageInfos:      file_urlshrt_proto_msgTypes,
	}.Build()
	File_urlshrt_proto = out.File
	file_urlshrt_proto_rawDesc = nil
	file_urlshrt_proto_goTypes = nil
	file_urlshrt_proto_depIdxs = nil
}
