name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.7
        with:
          repository: Yandex-Practicum/go-autotests
          tag: refactor
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Run statictest
        shell: bash
        run: |
            set +e
            err_output=$(go vet -vettool=$(which statictest) ./... 2>&1 >/dev/null)
            vet_exit_code=$?
            set -e
            if [[ -z "$err_output" ]]; then
              echo "No issues detected."
              exit 0
            elif [[ "$err_output" == "# github.com/PoorMercymain/urlshrt/pkg/api"*"error var _ should have name of the form errFoo" ]]; then
              echo "Detected allowed go vet message, proceeding."
              echo "$err_output"
              exit 0
            else
              echo "Unexpected issues found."
              echo "$err_output"
              exit 1
            fi
